name = "urlscanner"
main = "src/index.js"
compatibility_date = "2025-08-09"
compatibility_flags = [ "nodejs_als" ]

[[kv_namespaces]]
binding = "SCANS_KV"
id = "f9ac538dfe334910b80ee906368a4846"

[durable_objects]
bindings = [
  { name = "SCAN_POLL_DO", class_name = "ScanPollDO" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ScanPollDO"]

